# SConscript - 集成层 (Integration)
# 基础工程师维护的集成/胶水代码, 编译为工程私有目标并参与最终链接。
Import('env')
env.Append(CPPPATH=[
    Dir('inc'),
    '#ASW_Libs/inc', '#ASW_Libs/VehicleControl/inc', '#ASW_Libs/EnergyManagement/inc',
    '#BSW_Libs/inc', '#BSW_Libs/Etas/inc', '#BSW_Libs/Vector/inc',
    '#CDD_Libs/CddPwm/inc',
    '#Components/Common/inc', '#Components/Mcu/Sbm/inc',
    '#MCAL_Libs/inc',
])
objs = env.Object(Glob('src/*.c'))
Return('objs')
