/** @file     ASW_StbM_MemMap.h
  *
  * @brief    RTE Sample SWC MemMap file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.4.1 
  */

#if defined (START_WITH_IF)
#elif defined(ASW_StbM_START_SEC_CODE)
#undef ASW_StbM_START_SEC_CODE
#define RTE_START_SEC_APPL_CODE
#elif defined(ASW_StbM_STOP_SEC_CODE)
#undef ASW_StbM_STOP_SEC_CODE
#define RTE_STOP_SEC_APPL_CODE

#endif /* START_WITH_IF */

#include "Rte_MemMap.h"

