/** @file     CDD_CORE1_MemMap.h
  *
  * @brief    RTE Sample SWC MemMap file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  *
  * @note     Suppressed errors detected.
  *           E002118, E002118, E002118
  */

#if defined (START_WITH_IF)

/* Memory section of code */
#elif defined(CDD_CORE1_START_SEC_CODE)
	#undef CDD_CORE1_START_SEC_CODE
	#define RTE_START_SEC_EcucPartition_Core1_CODE
#elif defined(CDD_CORE1_STOP_SEC_CODE)
	#undef CDD_CORE1_STOP_SEC_CODE
	#define RTE_STOP_SEC_EcucPartition_Core1_CODE
/* Memory section of uninitialized variables */
#elif defined(CDD_CORE1_START_SEC_VAR_CLEARED_8)
	#undef CDD_CORE1_START_SEC_VAR_CLEARED_8
	#define RTE_START_SEC_EcucPartition_Core1_VAR_CLEARED_8
#elif defined(CDD_CORE1_STOP_SEC_VAR_CLEARED_8)
	#undef CDD_CORE1_STOP_SEC_VAR_CLEARED_8
	#define RTE_STOP_SEC_EcucPartition_Core1_VAR_CLEARED_8
#elif defined(CDD_CORE1_START_SEC_VAR_CLEARED_16)
	#undef CDD_CORE1_START_SEC_VAR_CLEARED_16
	#define RTE_START_SEC_EcucPartition_Core1_VAR_CLEARED_16
#elif defined(CDD_CORE1_STOP_SEC_VAR_CLEARED_16)
	#undef CDD_CORE1_STOP_SEC_VAR_CLEARED_16
	#define RTE_STOP_SEC_EcucPartition_Core1_VAR_CLEARED_16
#elif defined(CDD_CORE1_START_SEC_VAR_CLEARED_32)
	#undef CDD_CORE1_START_SEC_VAR_CLEARED_32
	#define RTE_START_SEC_EcucPartition_Core1_VAR_CLEARED_32
#elif defined(CDD_CORE1_STOP_SEC_VAR_CLEARED_32)
	#undef CDD_CORE1_STOP_SEC_VAR_CLEARED_32
	#define RTE_STOP_SEC_EcucPartition_Core1_VAR_CLEARED_32
#elif defined(CDD_CORE1_START_SEC_VAR_CLEARED_64)
	#undef CDD_CORE1_START_SEC_VAR_CLEARED_64
	#define RTE_START_SEC_EcucPartition_Core1_VAR_CLEARED_64
#elif defined(CDD_CORE1_STOP_SEC_VAR_CLEARED_64)
	#undef CDD_CORE1_STOP_SEC_VAR_CLEARED_64
	#define RTE_STOP_SEC_EcucPartition_Core1_VAR_CLEARED_64
#elif defined(CDD_CORE1_START_SEC_VAR_CLEARED_UNSPECIFIED)
	#undef CDD_CORE1_START_SEC_VAR_CLEARED_UNSPECIFIED
	#define RTE_START_SEC_EcucPartition_Core1_VAR_CLEARED_UNSPECIFIED
#elif defined(CDD_CORE1_STOP_SEC_VAR_CLEARED_UNSPECIFIED)
	#undef CDD_CORE1_STOP_SEC_VAR_CLEARED_UNSPECIFIED
	#define RTE_STOP_SEC_EcucPartition_Core1_VAR_CLEARED_UNSPECIFIED	
/* Memory section of initialized variables */	
#elif defined(CDD_CORE1_START_SEC_VAR_INIT_8)
	#undef CDD_CORE1_START_SEC_VAR_INIT_8
	#define RTE_START_SEC_EcucPartition_Core1_VAR_INIT_8
#elif defined(CDD_CORE1_STOP_SEC_VAR_INIT_8)
	#undef CDD_CORE1_STOP_SEC_VAR_INIT_8
	#define RTE_STOP_SEC_EcucPartition_Core1_VAR_INIT_8
#elif defined(CDD_CORE1_START_SEC_VAR_INIT_16)
	#undef CDD_CORE1_START_SEC_VAR_INIT_16
	#define RTE_START_SEC_EcucPartition_Core1_VAR_INIT_16
#elif defined(CDD_CORE1_STOP_SEC_VAR_INIT_16)
	#undef CDD_CORE1_STOP_SEC_VAR_INIT_16
	#define RTE_STOP_SEC_EcucPartition_Core1_VAR_INIT_16
#elif defined(CDD_CORE1_START_SEC_VAR_INIT_32)
	#undef CDD_CORE1_START_SEC_VAR_INIT_32
	#define RTE_START_SEC_EcucPartition_Core1_VAR_INIT_32
#elif defined(CDD_CORE1_STOP_SEC_VAR_INIT_32)
	#undef CDD_CORE1_STOP_SEC_VAR_INIT_32
	#define RTE_STOP_SEC_EcucPartition_Core1_VAR_INIT_32
#elif defined(CDD_CORE1_START_SEC_VAR_INIT_64)
	#undef CDD_CORE1_START_SEC_VAR_INIT_64
	#define RTE_START_SEC_EcucPartition_Core1_VAR_INIT_64
#elif defined(CDD_CORE1_STOP_SEC_VAR_INIT_64)
	#undef CDD_CORE1_STOP_SEC_VAR_INIT_64
	#define RTE_STOP_SEC_EcucPartition_Core1_VAR_INIT_64
#elif defined(CDD_CORE1_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef CDD_CORE1_START_SEC_VAR_INIT_UNSPECIFIED
	#define RTE_START_SEC_EcucPartition_Core1_VAR_INIT_UNSPECIFIED
#elif defined(CDD_CORE1_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef CDD_CORE1_STOP_SEC_VAR_INIT_UNSPECIFIED
	#define RTE_STOP_SEC_EcucPartition_Core1_VAR_INIT_UNSPECIFIED	
/* Memory section of constant */
#elif defined(CDD_CORE1_START_SEC_CONST_8)
	#undef CDD_CORE1_START_SEC_CONST_8
	#define RTE_START_SEC_EcucPartition_Core1_CONST_8
#elif defined(CDD_CORE1_STOP_SEC_CONST_8)
	#undef CDD_CORE1_STOP_SEC_CONST_8
	#define RTE_STOP_SEC_EcucPartition_Core1_CONST_8
#elif defined(CDD_CORE1_START_SEC_CONST_16)
	#undef CDD_CORE1_START_SEC_CONST_16
	#define RTE_START_SEC_EcucPartition_Core1_CONST_16
#elif defined(CDD_CORE1_STOP_SEC_CONST_16)
	#undef CDD_CORE1_STOP_SEC_CONST_16
	#define RTE_STOP_SEC_EcucPartition_Core1_CONST_16
#elif defined(CDD_CORE1_START_SEC_CONST_32)
	#undef CDD_CORE1_START_SEC_CONST_32
	#define RTE_START_SEC_EcucPartition_Core1_CONST_32
#elif defined(CDD_CORE1_STOP_SEC_CONST_32)
	#undef CDD_CORE1_STOP_SEC_CONST_32
	#define RTE_STOP_SEC_EcucPartition_Core1_CONST_32
#elif defined(CDD_CORE1_START_SEC_CONST_64)
	#undef CDD_CORE1_START_SEC_CONST_64
	#define RTE_START_SEC_EcucPartition_Core1_CONST_64
#elif defined(CDD_CORE1_STOP_SEC_CONST_64)
	#undef CDD_CORE1_STOP_SEC_CONST_64
	#define RTE_STOP_SEC_EcucPartition_Core1_CONST_64
#elif defined(CDD_CORE1_START_SEC_CONST_UNSPECIFIED)
	#undef CDD_CORE1_START_SEC_CONST_UNSPECIFIED
	#define RTE_START_SEC_EcucPartition_Core1_CONST_UNSPECIFIED
#elif defined(CDD_CORE1_STOP_SEC_CONST_UNSPECIFIED)
	#undef CDD_CORE1_STOP_SEC_CONST_UNSPECIFIED
	#define RTE_STOP_SEC_EcucPartition_Core1_CONST_UNSPECIFIED	

#else
	#error "CDD_CORE1, the section is undefined"

#endif /* START_WITH_IF */

#include "Rte_MemMap.h"

