/* Bsw_MemMap.h for AUTOSAR Memory Mapping R4.0 Rev 3 */
/* MISRA RULE 19.15 VIOLATION: MemMap header concept - no protection against repeated inclusion intended */


#if defined (START_WITH_IF)

/* VARIABLES */
#elif defined BSW_START_SEC_VAR_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_CLEARED_BOOLEAN
    #define CPU0_START_SEC_VAR_CLEARED_8      
#elif defined BSW_STOP_SEC_VAR_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_CLEARED_BOOLEAN
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_CLEARED_8
    #undef  BSW_START_SEC_VAR_CLEARED_8
    #define CPU0_START_SEC_VAR_CLEARED_8      
#elif defined BSW_STOP_SEC_VAR_CLEARED_8
    #undef BSW_STOP_SEC_VAR_CLEARED_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8      

#elif defined BSW_START_SEC_VAR_CLEARED_16
    #undef  BSW_START_SEC_VAR_CLEARED_16
    #define CPU0_START_SEC_VAR_CLEARED_16      
#elif defined BSW_STOP_SEC_VAR_CLEARED_16
    #undef BSW_STOP_SEC_VAR_CLEARED_16
    #define CPU0_STOP_SEC_VAR_CLEARED_16      

#elif defined BSW_START_SEC_VAR_CLEARED_32
    #undef  BSW_START_SEC_VAR_CLEARED_32
    #define CPU0_START_SEC_VAR_CLEARED_32      
#elif defined BSW_STOP_SEC_VAR_CLEARED_32
    #undef BSW_STOP_SEC_VAR_CLEARED_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED      
#elif defined BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_SHARED_START_SEC_VAR_CLEARED_BOOLEAN
    #undef  BSW_SHARED_START_SEC_VAR_CLEARED_BOOLEAN
    #define SHARED_START_SEC_VAR_CLEARED_8      
#elif defined BSW_SHARED_STOP_SEC_VAR_CLEARED_BOOLEAN
    #undef BSW_SHARED_STOP_SEC_VAR_CLEARED_BOOLEAN
    #define SHARED_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_SHARED_START_SEC_VAR_CLEARED_8
    #undef  BSW_SHARED_START_SEC_VAR_CLEARED_8
    #define SHARED_START_SEC_VAR_CLEARED_8      
#elif defined BSW_SHARED_STOP_SEC_VAR_CLEARED_8
    #undef BSW_SHARED_STOP_SEC_VAR_CLEARED_8
    #define SHARED_STOP_SEC_VAR_CLEARED_8      

#elif defined BSW_SHARED_START_SEC_VAR_CLEARED_16
    #undef  BSW_SHARED_START_SEC_VAR_CLEARED_16
    #define SHARED_START_SEC_VAR_CLEARED_16      
#elif defined BSW_SHARED_STOP_SEC_VAR_CLEARED_16
    #undef BSW_SHARED_STOP_SEC_VAR_CLEARED_16
    #define SHARED_STOP_SEC_VAR_CLEARED_16      

#elif defined BSW_SHARED_START_SEC_VAR_CLEARED_32
    #undef  BSW_SHARED_START_SEC_VAR_CLEARED_32
    #define SHARED_START_SEC_VAR_CLEARED_32      
#elif defined BSW_SHARED_STOP_SEC_VAR_CLEARED_32
    #undef BSW_SHARED_STOP_SEC_VAR_CLEARED_32
    #define SHARED_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_SHARED_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef  BSW_SHARED_START_SEC_VAR_CLEARED_UNSPECIFIED
    #define SHARED_START_SEC_VAR_CLEARED_UNSPECIFIED      
#elif defined BSW_SHARED_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_SHARED_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #define SHARED_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_8
    #undef  BSW_START_SEC_VAR_POWER_ON_CLEARED_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_16
    #undef  BSW_START_SEC_VAR_POWER_ON_CLEARED_16
    #define CPU0_START_SEC_VAR_CLEARED_16
#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_16
    #define CPU0_STOP_SEC_VAR_CLEARED_16

#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_32
    #undef  BSW_START_SEC_VAR_POWER_ON_CLEARED_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_INIT_BOOLEAN
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_INIT_BOOLEAN
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_INIT_8
    #undef  BSW_START_SEC_VAR_INIT_8
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_INIT_8
    #undef BSW_STOP_SEC_VAR_INIT_8
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_INIT_16
    #undef  BSW_START_SEC_VAR_INIT_16
    #define CPU0_START_SEC_VAR_INIT_16
#elif defined BSW_STOP_SEC_VAR_INIT_16
    #undef BSW_STOP_SEC_VAR_INIT_16
    #define CPU0_STOP_SEC_VAR_INIT_16

#elif defined BSW_START_SEC_VAR_INIT_32
    #undef  BSW_START_SEC_VAR_INIT_32
    #define CPU0_START_SEC_VAR_INIT_32
#elif defined BSW_STOP_SEC_VAR_INIT_32
    #undef BSW_STOP_SEC_VAR_INIT_32
    #define CPU0_STOP_SEC_VAR_INIT_32

#elif defined BSW_START_SEC_VAR_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_INIT_UNSPECIFIED
    #define CPU0_START_SEC_VAR_INIT_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_SHARED_START_SEC_VAR_INIT_BOOLEAN
    #undef  BSW_SHARED_START_SEC_VAR_INIT_BOOLEAN
    #define SHARED_START_SEC_VAR_INIT_8      
#elif defined BSW_SHARED_STOP_SEC_VAR_INIT_BOOLEAN
    #undef BSW_SHARED_STOP_SEC_VAR_INIT_BOOLEAN
    #define SHARED_STOP_SEC_VAR_INIT_8

#elif defined BSW_SHARED_START_SEC_VAR_INIT_8
    #undef  BSW_SHARED_START_SEC_VAR_INIT_8
    #define SHARED_START_SEC_VAR_INIT_8      
#elif defined BSW_SHARED_STOP_SEC_VAR_INIT_8
    #undef BSW_SHARED_STOP_SEC_VAR_INIT_8
    #define SHARED_STOP_SEC_VAR_INIT_8      

#elif defined BSW_SHARED_START_SEC_VAR_INIT_16
    #undef  BSW_SHARED_START_SEC_VAR_INIT_16
    #define SHARED_START_SEC_VAR_INIT_16      
#elif defined BSW_SHARED_STOP_SEC_VAR_INIT_16
    #undef BSW_SHARED_STOP_SEC_VAR_INIT_16
    #define SHARED_STOP_SEC_VAR_INIT_16      

#elif defined BSW_SHARED_START_SEC_VAR_INIT_32
    #undef  BSW_SHARED_START_SEC_VAR_INIT_32
    #define SHARED_START_SEC_VAR_INIT_32      
#elif defined BSW_SHARED_STOP_SEC_VAR_INIT_32
    #undef BSW_SHARED_STOP_SEC_VAR_INIT_32
    #define SHARED_STOP_SEC_VAR_INIT_32

#elif defined BSW_SHARED_START_SEC_VAR_INIT_UNSPECIFIED
    #undef  BSW_SHARED_START_SEC_VAR_INIT_UNSPECIFIED
    #define SHARED_START_SEC_VAR_INIT_UNSPECIFIED      
#elif defined BSW_SHARED_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_SHARED_STOP_SEC_VAR_INIT_UNSPECIFIED
    #define SHARED_STOP_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_8
    #undef  BSW_START_SEC_VAR_POWER_ON_INIT_8
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_8
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_16
    #undef  BSW_START_SEC_VAR_POWER_ON_INIT_16
    #define CPU0_START_SEC_VAR_INIT_16
#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_16
    #define CPU0_STOP_SEC_VAR_INIT_16


#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_32
    #undef  BSW_START_SEC_VAR_POWER_ON_INIT_32
    #define CPU0_START_SEC_VAR_INIT_32
#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_32
    #define CPU0_STOP_SEC_VAR_INIT_32

#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #define CPU0_START_SEC_VAR_INIT_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_FAST_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_FAST_CLEARED_BOOLEAN
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_FAST_CLEARED_8
    #undef  BSW_START_SEC_VAR_FAST_CLEARED_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_8
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_FAST_CLEARED_16
    #undef  BSW_START_SEC_VAR_FAST_CLEARED_16
    #define CPU0_START_SEC_VAR_CLEARED_16
#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_16
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_16
    #define CPU0_STOP_SEC_VAR_CLEARED_16

#elif defined BSW_START_SEC_VAR_FAST_CLEARED_32
    #undef  BSW_START_SEC_VAR_FAST_CLEARED_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_32
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
    #define CPU0_START_SEC_VAR_CLEARED_16
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
    #define CPU0_STOP_SEC_VAR_CLEARED_16

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_FAST_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_FAST_INIT_BOOLEAN
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_FAST_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_INIT_BOOLEAN
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_FAST_INIT_8
    #undef  BSW_START_SEC_VAR_FAST_INIT_8
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_FAST_INIT_8
    #undef BSW_STOP_SEC_VAR_FAST_INIT_8
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_FAST_INIT_16
    #undef  BSW_START_SEC_VAR_FAST_INIT_16
    #define CPU0_START_SEC_VAR_INIT_16
#elif defined BSW_STOP_SEC_VAR_FAST_INIT_16
    #undef BSW_STOP_SEC_VAR_FAST_INIT_16
    #define CPU0_STOP_SEC_VAR_INIT_16

#elif defined BSW_START_SEC_VAR_FAST_INIT_32
    #undef  BSW_START_SEC_VAR_FAST_INIT_32
    #define CPU0_START_SEC_VAR_INIT_32
#elif defined BSW_STOP_SEC_VAR_FAST_INIT_32
    #undef BSW_STOP_SEC_VAR_FAST_INIT_32
    #define CPU0_STOP_SEC_VAR_INIT_32

#elif defined BSW_START_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_FAST_INIT_UNSPECIFIED
    #define CPU0_START_SEC_VAR_INIT_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_8
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_INIT_8
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_16
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_INIT_16
     #define CPU0_START_SEC_VAR_INIT_16
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
     #define CPU0_STOP_SEC_VAR_INIT_16

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_32
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_INIT_32
    #define CPU0_START_SEC_VAR_INIT_32
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
    #define CPU0_STOP_SEC_VAR_INIT_32

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
    #define CPU0_START_SEC_VAR_INIT_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_8
    #undef  BSW_START_SEC_VAR_SLOW_CLEARED_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_8
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_16
    #undef  BSW_START_SEC_VAR_SLOW_CLEARED_16
    #define CPU0_START_SEC_VAR_CLEARED_16
#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_16
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_16
    #define CPU0_STOP_SEC_VAR_CLEARED_16

#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_32
    #undef  BSW_START_SEC_VAR_SLOW_CLEARED_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_32
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
    #define CPU0_START_SEC_VAR_CLEARED_16
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
    #define CPU0_STOP_SEC_VAR_CLEARED_16

#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_SLOW_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_SLOW_INIT_BOOLEAN
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_SLOW_INIT_8
    #undef  BSW_START_SEC_VAR_SLOW_INIT_8
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_8
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_8
    #define CPU0_STOP_SEC_VAR_INIT_8
    
#elif defined BSW_START_SEC_VAR_SLOW_INIT_16
    #undef  BSW_START_SEC_VAR_SLOW_INIT_16
    #define CPU0_START_SEC_VAR_INIT_16
#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_16
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_16
    #define CPU0_STOP_SEC_VAR_INIT_16

#elif defined BSW_START_SEC_VAR_SLOW_INIT_32
    #undef  BSW_START_SEC_VAR_SLOW_INIT_32
    #define CPU0_START_SEC_VAR_INIT_32
#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_32
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_32
    #define CPU0_STOP_SEC_VAR_INIT_32

#elif defined BSW_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
    #define CPU0_START_SEC_VAR_INIT_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_8
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_8
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
    #define CPU0_STOP_SEC_VAR_INIT_8


#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_16
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_16
    #define CPU0_START_SEC_VAR_INIT_16
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
    #define CPU0_STOP_SEC_VAR_INIT_16


#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_32
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_32
    #define CPU0_START_SEC_VAR_INIT_32
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
    #define CPU0_STOP_SEC_VAR_INIT_32


#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
    #define CPU0_START_SEC_VAR_INIT_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_8
    #undef  BSW_START_SEC_INTERNAL_VAR_CLEARED_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_16
    #undef  BSW_START_SEC_INTERNAL_VAR_CLEARED_16
    #define CPU0_START_SEC_VAR_CLEARED_16
#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_16
    #define CPU0_STOP_SEC_VAR_CLEARED_16

#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_32
    #undef  BSW_START_SEC_INTERNAL_VAR_CLEARED_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
    #define CPU0_START_SEC_VAR_CLEARED_16
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #undef  BSW_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_8
    #undef  BSW_START_SEC_INTERNAL_VAR_INIT_8
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_8
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_16
    #undef  BSW_START_SEC_INTERNAL_VAR_INIT_16
    #define CPU0_START_SEC_VAR_INIT_16
#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_16
    #define CPU0_STOP_SEC_VAR_INIT_16

#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_32
    #undef  BSW_START_SEC_INTERNAL_VAR_INIT_32
    #define CPU0_START_SEC_VAR_INIT_32
#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_32
    #define CPU0_STOP_SEC_VAR_INIT_32

#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #define CPU0_START_SEC_VAR_INIT_UNSPECIFIED
#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #define CPU0_START_SEC_VAR_INIT_16
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #define CPU0_STOP_SEC_VAR_INIT_16

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #define CPU0_START_SEC_VAR_INIT_32
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #define CPU0_STOP_SEC_VAR_INIT_32

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef  BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #define CPU0_START_SEC_VAR_INIT_UNSPECIFIED
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_SAVED_ZONE_BOOLEAN
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_BOOLEAN
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_SAVED_ZONE_8
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_8
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_SAVED_ZONE_16
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_16
    #define CPU0_START_SEC_VAR_CLEARED_16
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_16
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_16
    #define CPU0_STOP_SEC_VAR_CLEARED_16

#elif defined BSW_START_SEC_VAR_SAVED_ZONE_32
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_32
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #define CPU0_START_SEC_VAR_INIT_UNSPECIFIED
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_8
    #define CPU0_START_SEC_VAR_INIT_8
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_8
    #define CPU0_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_16
    #define CPU0_START_SEC_VAR_CLEARED_16
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16
    #define CPU0_STOP_SEC_VAR_CLEARED_16

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_16
    #define CPU0_START_SEC_VAR_INIT_16
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_16
    #define CPU0_STOP_SEC_VAR_INIT_16

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_32
    #define CPU0_START_SEC_VAR_INIT_32
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_32
    #define CPU0_STOP_SEC_VAR_INIT_32
/* CONSTANTS */
#elif defined BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
#elif defined BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_CONST_8
    #undef BSW_START_SEC_DEFAULT_CONST_8
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_DEFAULT_CONST_8
    #undef BSW_STOP_SEC_DEFAULT_CONST_8
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_DEFAULT_CONST_16
    #undef BSW_START_SEC_DEFAULT_CONST_16
    #define CPU0_START_SEC_CONST_16 
#elif defined BSW_STOP_SEC_DEFAULT_CONST_16
    #undef BSW_STOP_SEC_DEFAULT_CONST_16
    #define CPU0_STOP_SEC_CONST_16

#elif defined BSW_START_SEC_DEFAULT_CONST_32
    #undef BSW_START_SEC_DEFAULT_CONST_32
    #define CPU0_START_SEC_CONST_32
#elif defined BSW_STOP_SEC_DEFAULT_CONST_32
    #undef BSW_STOP_SEC_DEFAULT_CONST_32
    #define CPU0_STOP_SEC_CONST_32

#elif defined BSW_START_SEC_CONST_BOOLEAN
    #undef  BSW_START_SEC_CONST_BOOLEAN
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONST_BOOLEAN
    #undef BSW_STOP_SEC_CONST_BOOLEAN
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONST_8
    #undef  BSW_START_SEC_CONST_8
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONST_8
    #undef BSW_STOP_SEC_CONST_8
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONST_16
    #undef  BSW_START_SEC_CONST_16
    #define CPU0_START_SEC_CONST_16
#elif defined BSW_STOP_SEC_CONST_16
    #undef BSW_STOP_SEC_CONST_16
    #define CPU0_STOP_SEC_CONST_16

#elif defined BSW_START_SEC_CONST_32
    #undef  BSW_START_SEC_CONST_32
    #define CPU0_START_SEC_CONST_32
#elif defined BSW_STOP_SEC_CONST_32
    #undef BSW_STOP_SEC_CONST_32
    #define CPU0_STOP_SEC_CONST_32

#elif defined BSW_START_SEC_CONST_UNSPECIFIED
    #undef  BSW_START_SEC_CONST_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
#elif defined BSW_STOP_SEC_CONST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED

#elif defined BSW_START_SEC_CONST_FAST_BOOLEAN
    #undef  BSW_START_SEC_CONST_FAST_BOOLEAN
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONST_FAST_BOOLEAN
    #undef BSW_STOP_SEC_CONST_FAST_BOOLEAN
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONST_FAST_8
    #undef  BSW_START_SEC_CONST_FAST_8
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONST_FAST_8
    #undef BSW_STOP_SEC_CONST_FAST_8
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONST_FAST_16
    #undef  BSW_START_SEC_CONST_FAST_16
    #define CPU0_START_SEC_CONST_16
#elif defined BSW_STOP_SEC_CONST_FAST_16
    #undef BSW_STOP_SEC_CONST_FAST_16
    #define CPU0_STOP_SEC_CONST_16

#elif defined BSW_START_SEC_CONST_FAST_32
    #undef  BSW_START_SEC_CONST_FAST_32
    #define CPU0_START_SEC_CONST_32
#elif defined BSW_STOP_SEC_CONST_FAST_32
    #undef BSW_STOP_SEC_CONST_FAST_32
    #define CPU0_STOP_SEC_CONST_32

#elif defined BSW_START_SEC_CONST_FAST_UNSPECIFIED
    #undef  BSW_START_SEC_CONST_FAST_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
#elif defined BSW_STOP_SEC_CONST_FAST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_FAST_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED

#elif defined BSW_START_SEC_CONST_SLOW_BOOLEAN
    #undef  BSW_START_SEC_CONST_SLOW_BOOLEAN
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONST_SLOW_BOOLEAN
    #undef BSW_STOP_SEC_CONST_SLOW_BOOLEAN
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONST_SLOW_8
    #undef  BSW_START_SEC_CONST_SLOW_8
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONST_SLOW_8
    #undef BSW_STOP_SEC_CONST_SLOW_8
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONST_SLOW_16
    #undef  BSW_START_SEC_CONST_SLOW_16
    #define CPU0_START_SEC_CONST_16
#elif defined BSW_STOP_SEC_CONST_SLOW_16
    #undef BSW_STOP_SEC_CONST_SLOW_16
    #define CPU0_STOP_SEC_CONST_16

#elif defined BSW_START_SEC_CONST_SLOW_32
    #undef  BSW_START_SEC_CONST_SLOW_32
    #define CPU0_START_SEC_CONST_32 
#elif defined BSW_STOP_SEC_CONST_SLOW_32
    #undef BSW_STOP_SEC_CONST_SLOW_32
    #define CPU0_STOP_SEC_CONST_32

#elif defined BSW_START_SEC_CONST_SLOW_UNSPECIFIED
    #undef  BSW_START_SEC_CONST_SLOW_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
#elif defined BSW_STOP_SEC_CONST_SLOW_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_SLOW_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED

#elif defined BSW_START_SEC_CALIB_BOOLEAN
    #undef  BSW_START_SEC_CALIB_BOOLEAN

#elif defined BSW_STOP_SEC_CALIB_BOOLEAN
    #undef BSW_STOP_SEC_CALIB_BOOLEAN

#elif defined BSW_START_SEC_CALIB_8
    #undef  BSW_START_SEC_CALIB_8

#elif defined BSW_STOP_SEC_CALIB_8
    #undef BSW_STOP_SEC_CALIB_8

#elif defined BSW_START_SEC_CALIB_16
    #undef  BSW_START_SEC_CALIB_16

#elif defined BSW_STOP_SEC_CALIB_16
    #undef BSW_STOP_SEC_CALIB_16

#elif defined BSW_START_SEC_CALIB_32
    #undef  BSW_START_SEC_CALIB_32

#elif defined BSW_STOP_SEC_CALIB_32
    #undef BSW_STOP_SEC_CALIB_32

#elif defined BSW_START_SEC_CALIB_UNSPECIFIED
    #undef  BSW_START_SEC_CALIB_UNSPECIFIED

#elif defined BSW_STOP_SEC_CALIB_UNSPECIFIED
    #undef BSW_STOP_SEC_CALIB_UNSPECIFIED

#elif defined BSW_START_SEC_CALIB_FAST_BOOLEAN
    #undef  BSW_START_SEC_CALIB_FAST_BOOLEAN

#elif defined BSW_STOP_SEC_CALIB_FAST_BOOLEAN
    #undef BSW_STOP_SEC_CALIB_FAST_BOOLEAN

#elif defined BSW_START_SEC_CALIB_FAST_8
    #undef  BSW_START_SEC_CALIB_FAST_8

#elif defined BSW_STOP_SEC_CALIB_FAST_8
    #undef BSW_STOP_SEC_CALIB_FAST_8

#elif defined BSW_START_SEC_CALIB_FAST_16
    #undef  BSW_START_SEC_CALIB_FAST_16

#elif defined BSW_STOP_SEC_CALIB_FAST_16
    #undef BSW_STOP_SEC_CALIB_FAST_16

#elif defined BSW_START_SEC_CALIB_FAST_32
    #undef  BSW_START_SEC_CALIB_FAST_32

#elif defined BSW_STOP_SEC_CALIB_FAST_32
    #undef BSW_STOP_SEC_CALIB_FAST_32

#elif defined BSW_START_SEC_CALIB_FAST_UNSPECIFIED
    #undef  BSW_START_SEC_CALIB_FAST_UNSPECIFIED

#elif defined BSW_STOP_SEC_CALIB_FAST_UNSPECIFIED
    #undef BSW_STOP_SEC_CALIB_FAST_UNSPECIFIED

#elif defined BSW_START_SEC_CALIB_SLOW_BOOLEAN
    #undef  BSW_START_SEC_CALIB_SLOW_BOOLEAN

#elif defined BSW_STOP_SEC_CALIB_SLOW_BOOLEAN
    #undef BSW_STOP_SEC_CALIB_SLOW_BOOLEAN

#elif defined BSW_START_SEC_CALIB_SLOW_8
    #undef  BSW_START_SEC_CALIB_SLOW_8

#elif defined BSW_STOP_SEC_CALIB_SLOW_8
    #undef BSW_STOP_SEC_CALIB_SLOW_8

#elif defined BSW_START_SEC_CALIB_SLOW_16
    #undef  BSW_START_SEC_CALIB_SLOW_16

#elif defined BSW_STOP_SEC_CALIB_SLOW_16
    #undef BSW_STOP_SEC_CALIB_SLOW_16

#elif defined BSW_START_SEC_CALIB_SLOW_32
    #undef  BSW_START_SEC_CALIB_SLOW_32

#elif defined BSW_STOP_SEC_CALIB_SLOW_32
    #undef BSW_STOP_SEC_CALIB_SLOW_32

#elif defined BSW_START_SEC_CALIB_SLOW_UNSPECIFIED
    #undef  BSW_START_SEC_CALIB_SLOW_UNSPECIFIED

#elif defined BSW_STOP_SEC_CALIB_SLOW_UNSPECIFIED
    #undef BSW_STOP_SEC_CALIB_SLOW_UNSPECIFIED

#elif defined BSW_START_SEC_CONFIG_DATA_BOOLEAN
    #undef  BSW_START_SEC_CONFIG_DATA_BOOLEAN
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONFIG_DATA_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_BOOLEAN
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONFIG_DATA_8
    #undef  BSW_START_SEC_CONFIG_DATA_8
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONFIG_DATA_8
    #undef BSW_STOP_SEC_CONFIG_DATA_8
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONFIG_DATA_16
    #undef  BSW_START_SEC_CONFIG_DATA_16
    #define CPU0_START_SEC_CONST_16
#elif defined BSW_STOP_SEC_CONFIG_DATA_16
    #undef BSW_STOP_SEC_CONFIG_DATA_16
    #define CPU0_STOP_SEC_CONST_16

#elif defined BSW_START_SEC_CONFIG_DATA_32
    #undef  BSW_START_SEC_CONFIG_DATA_32
    #define CPU0_START_SEC_CONST_32
#elif defined BSW_STOP_SEC_CONFIG_DATA_32
    #undef BSW_STOP_SEC_CONFIG_DATA_32
    #define CPU0_STOP_SEC_CONST_32

#elif defined BSW_START_SEC_CONFIG_DATA_UNSPECIFIED
    #undef  BSW_START_SEC_CONFIG_DATA_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
#elif defined BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED

#elif defined BSW_START_SEC_CONFIG_DATA_FAST_BOOLEAN
    #undef  BSW_START_SEC_CONFIG_DATA_FAST_BOOLEAN
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_BOOLEAN
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONFIG_DATA_FAST_8
    #undef  BSW_START_SEC_CONFIG_DATA_FAST_8
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_8
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_8
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONFIG_DATA_FAST_16
    #undef  BSW_START_SEC_CONFIG_DATA_FAST_16
    #define CPU0_START_SEC_CONST_16
#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_16
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_16
    #define CPU0_STOP_SEC_CONST_16

#elif defined BSW_START_SEC_CONFIG_DATA_FAST_32
    #undef  BSW_START_SEC_CONFIG_DATA_FAST_32
    #define CPU0_START_SEC_CONST_32
#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_32
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_32
    #define CPU0_STOP_SEC_CONST_32

#elif defined BSW_START_SEC_CONFIG_DATA_FAST_UNSPECIFIED
    #undef  BSW_START_SEC_CONFIG_DATA_FAST_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED

#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_BOOLEAN
    #undef  BSW_START_SEC_CONFIG_DATA_SLOW_BOOLEAN
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_BOOLEAN
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_8
    #undef  BSW_START_SEC_CONFIG_DATA_SLOW_8
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_8
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_8
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_16
    #undef  BSW_START_SEC_CONFIG_DATA_SLOW_16
    #define CPU0_START_SEC_CONST_16
#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_16
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_16
    #define CPU0_STOP_SEC_CONST_16

#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_32
    #undef  BSW_START_SEC_CONFIG_DATA_SLOW_32
    #define CPU0_START_SEC_CONST_32
#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_32
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_32
    #define CPU0_STOP_SEC_CONST_32

#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
    #undef  BSW_START_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_HEADER
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_HEADER
    #define CPU0_START_SEC_CONST_UNSPECIFIED
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_8
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_8
    #define CPU0_START_SEC_CONST_8
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_8
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_8
    #define CPU0_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_16
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_16
    #define CPU0_START_SEC_CONST_16
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_16
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_16
    #define CPU0_STOP_SEC_CONST_16

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_32
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_32
    #define CPU0_START_SEC_CONST_32
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32
    #define CPU0_STOP_SEC_CONST_32

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef  BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #define CPU0_START_SEC_CONST_UNSPECIFIED
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #define CPU0_STOP_SEC_CONST_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE
    #undef  BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE

#elif defined BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE
    #undef BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE


#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_32
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_32
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_SPRAM_CODE
    #undef BSW_START_SEC_SPRAM_CODE
    #define CPU0_START_SEC_CODE
#elif defined BSW_STOP_SEC_SPRAM_CODE
    #undef BSW_STOP_SEC_SPRAM_CODE
    #define CPU0_STOP_SEC_CODE

/* CODE */
#elif defined BSW_START_SEC_DEFAULT_CODE
    #undef BSW_START_SEC_DEFAULT_CODE
    #define CPU0_START_SEC_CODE
#elif defined BSW_STOP_SEC_DEFAULT_CODE
    #undef BSW_STOP_SEC_DEFAULT_CODE
    #define CPU0_STOP_SEC_CODE

#elif defined BSW_START_SEC_CODE
    #undef  BSW_START_SEC_CODE
    #define CPU0_START_SEC_CODE
#elif defined BSW_STOP_SEC_CODE
    #undef BSW_STOP_SEC_CODE
    #define CPU0_STOP_SEC_CODE

#elif defined BSW_SHARED_START_SEC_CODE
    #undef  BSW_SHARED_START_SEC_CODE
    #define SHARED_START_SEC_CODE
#elif defined BSW_SHARED_STOP_SEC_CODE
    #undef BSW_SHARED_STOP_SEC_CODE
    #define SHARED_STOP_SEC_CODE

#elif defined BSW_START_SEC_DEFAULT_CONST_32
    #undef BSW_START_SEC_DEFAULT_CONST_32
    #define CPU0_START_SEC_CONST_32
#elif defined BSW_STOP_SEC_DEFAULT_CONST_32
    #undef BSW_STOP_SEC_DEFAULT_CONST_32
    #define CPU0_STOP_SEC_CONST_32

#elif defined BSW_START_SEC_CODE_FAST
    #undef  BSW_START_SEC_CODE_FAST
    #define CPU0_START_SEC_CODE
#elif defined BSW_STOP_SEC_CODE_FAST
    #undef BSW_STOP_SEC_CODE_FAST
    #define CPU0_STOP_SEC_CODE

#elif defined BSW_START_SEC_CODE_SLOW
    #undef  BSW_START_SEC_CODE_SLOW
    #define CPU0_START_SEC_CODE
#elif defined BSW_STOP_SEC_CODE_SLOW
    #undef BSW_STOP_SEC_CODE_SLOW
    #define CPU0_STOP_SEC_CODE

#elif defined BSW_START_SEC_CODE_LIB
    #undef  BSW_START_SEC_CODE_LIB
    #define CPU0_START_SEC_CODE
#elif defined BSW_STOP_SEC_CODE_LIB
    #undef BSW_STOP_SEC_CODE_LIB
    #define CPU0_STOP_SEC_CODE

/* USER DEFINED */

#elif defined BSW_START_SEC_SAVED_ZONE_8
    #undef  BSW_START_SEC_SAVED_ZONE_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_SAVED_ZONE_8
    #undef BSW_STOP_SEC_SAVED_ZONE_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_SAVED_ZONE_16
    #undef  BSW_START_SEC_SAVED_ZONE_16
    #define CPU0_START_SEC_VAR_CLEARED_16
#elif defined BSW_STOP_SEC_SAVED_ZONE_16
    #undef BSW_STOP_SEC_SAVED_ZONE_16
    #define CPU0_STOP_SEC_VAR_CLEARED_16

#elif defined BSW_START_SEC_SAVED_ZONE_32
    #undef  BSW_START_SEC_SAVED_ZONE_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_SAVED_ZONE_32
    #undef BSW_STOP_SEC_SAVED_ZONE_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_SAVED_ZONE_UNSPECIFIED
    #undef  BSW_START_SEC_SAVED_ZONE_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_SAVED_ZONE_UNSPECIFIED
    #undef BSW_STOP_SEC_SAVED_ZONE_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    
#elif defined BSW_START_SEC_CALLOUT_CODE
    #undef  BSW_START_SEC_CALLOUT_CODE
    #define CPU0_START_SEC_CODE
#elif defined BSW_STOP_SEC_CALLOUT_CODE
    #undef BSW_STOP_SEC_CALLOUT_CODE
    #define CPU0_STOP_SEC_CODE

#elif defined BSW_START_SEC_VAR_CLEARED_8_SECURED
    #undef  BSW_START_SEC_VAR_CLEARED_8_SECURED
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_CLEARED_8_SECURED
    #undef BSW_STOP_SEC_VAR_CLEARED_8_SECURED
    #define CPU0_STOP_SEC_VAR_CLEARED_8
    
#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_8
    #undef  BSW_START_SEC_VAR_CLEARED_SECURED_8
    #define CPU0_START_SEC_VAR_CLEARED_8
#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_8
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_8
    #define CPU0_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_CLEARED_32_SECURED
    #undef  BSW_START_SEC_VAR_CLEARED_32_SECURED
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_VAR_CLEARED_32_SECURED
    #undef BSW_STOP_SEC_VAR_CLEARED_32_SECURED
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_32
    #undef  BSW_START_SEC_VAR_CLEARED_SECURED_32
    #define CPU0_START_SEC_VAR_CLEARED_32
#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_32
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_32
    #define CPU0_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_VAR_CLEARED_UNSPECIFIED_SECURED
    #undef  BSW_START_SEC_VAR_CLEARED_UNSPECIFIED_SECURED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED_SECURED
    #undef BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED_SECURED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_CLEARED_SECURED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
    #undef  BSW_START_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
    #define CPU0_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
    #define CPU0_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#else
    #error "Bsw_MemMap.h, memmap section unconfigured"
#endif

#include "MemMap.h"
