

#ifndef RBA_ETHDHCPCLIENT_TYPES_H
#define RBA_ETHDHCPCLIENT_TYPES_H

#if ( defined(TCPIP_DHCP_CLIENT_ENABLED) && ( TCPIP_DHCP_CLIENT_ENABLED == STD_ON ) )

/* DHCP client state */
typedef enum
{
    RBA_ETHDHCP_CLNTOFF     = 0,
    RBA_ETHDHCP_CLNTINIT,
    RBA_ETHDHCP_CLNTSELECTING,
    RBA_ETHDHCP_CLNTREQUESTING,
    RBA_ETHDHCP_CLNTPROBING,
    RBA_ETHDHCP_CLNTBOUND,
    RBA_ETHDHCP_CLNTRENEWING,
    RBA_ETHDHCP_CLNTREBINDING,
    RBA_ETHDHCP_CLNTREBOOTING,
    RBA_ETHDHCP_CLNTINFORMING,
    RBA_ETHDHCP_CLNTDECLINE,
    RBA_ETHDHCP_CLNTPERMANENT,
    RBA_ETHDHCP_CLNTSTOP,
    RBA_ETHDHCP_CLNTRELEASE
} rba_EthDHCPClient_State_ten;

/*
 * DHCP Server state
 * States used by the client process to know if a response
 * and which kind of response has been received.
 */
typedef enum
{
    RBA_ETHDHCP_SRVROFF     = 0,
    RBA_ETHDHCP_SRVROFFER,
    RBA_ETHDHCP_SRVRACK,
    RBA_ETHDHCP_SRVRNACK,
    RBA_ETHDHCP_SRVRWAITRESP
} rba_EthDHCPServer_State_ten;

/* Parameters got from the DHCP Server and used by TcpIP
 * to use the dynamic IP Address assigned  */
typedef struct
{
    uint32      clientIpAddress_u32;
    uint32      clientSubnetMask_u32;
    uint32      clientIpRouter_u32;
}rba_EthDHCPClient_AssignmentParameters_tst;

/*
 * DHCPClient table used to store the current status
 * of the client and information received from the Server
 */
typedef struct
{
    rba_EthDHCP_SockState_ten       procSocketState_ten;                            /* State of the Client Socket */
    rba_EthDHCPClient_State_ten     procState_ten;                                  /* State of the DHCP Client entry */
    rba_EthDHCPServer_State_ten     serverRespType_ten;                             /* Type of the latest response received from the server */
    TcpIp_IpAddrStateType           clientIpAddressState_en;                        /* IP address state (assigned / unassigned) */
    uint32                          procCnt_u32;                                    /* Time Counter to temporize or to integrate delay in the process */
    uint32                          procReTransmissionTime_u32;                     /* Retransmission time updated after each retransmission */
    uint32                          procCntLastConflict_u32;                        /* Counter updated to calculate the min interval accepted after a conflict */
    uint32                          procCntTxFr_u32;                                /* Counter to count the number of frames send in the case of retransmission */
    uint32                          clientXId_u32;                                  /* XiD generated by the client                                  */
    uint32                          clientXIdInform_u32;                            /* XiD generated by the client                                  */
    uint32                          clientIpAddress_u32;                            /* Offered address received from the server                     */
    uint32                          clientLeaseTickTime_u32;                        /* Lease  Time converted as Tick Time to use in the process     */
    uint32                          clientRenewTickTime_u32;                        /* Renew  Time converted as Tick Time to use in the process     */
    uint32                          clientRebindTickTime_u32;                       /* Rebind Time converted as Tick Time to use in the process     */
    uint32                          clientLeaseDeltaTickTime_u32;                   /* This is the time elapsed between first DHCP REQUEST and DHCP ACK */
    uint32                          serverIpAddress_u32;                            /* IP address of the server                             */
    uint32                          serverId_u32;                                   /* Server ID                                            */
    uint32                          optionServerId_u32;
    uint32                          optionLeaseTime_u32;
    uint32                          optionSubnetMaskId_u32;
    uint32                          optionRouter_u32;
    uint32                          optionRenewalTime_u32;
    uint32                          optionRebindingTime_u32;
    uint32                          optionClientId_u32;
    uint16                          KwnFQDNLen_u16;                              /* Holds the length of the FQDN */
    uint16                          ReqFQDNLen_u16;                              /* Holds the length of the Requested FQDN*/


    TcpIp_SocketIdType              procSocketId_u16;                               /* Client Socket Id */

    uint8                           clientHwAddr_au8[RBA_ETHDHCP_CHADDR_LENGTH];    /* DHCP Client MAC address */
    uint8                           procCntConflict_u8;                             /* Count the number of conflicts */
    uint8                           procCntTxProbeFr_u8;                            /* ARP Probe Frame sent counter */
    uint8                           procCntTxGratuFr_u8;                            /* ARP Gratuitous Frame sent counter */
    uint8                           procCntTxRlsFrmAttempts_u8;                     /* Number of release messages TX tried */
    uint8                           optionMessType_u8;
    uint8                           optionParamRqstList_au8[RBA_ETHDHCP_OPTION_PARAMRQSTLIST_LENGTH];
    uint8                           KwnFQDNBuf_au8[RBA_ETHDHCP_OPTION_FQDN_MAX_LENGTH]; /* Buffer for the FQDN  */
    uint8                           ReqFQDNBuf_au8[RBA_ETHDHCP_OPTION_FQDN_MAX_LENGTH]; /* Buffer for the Requested FQDN  */
    boolean                         optionClientIdFlag_b;                           /* Flag to disable enable Client Identification Option  */
    boolean                         optionParamRqstListFlag_b;                      /* Flag to disable enable Requested Parameter Option    */
    boolean                         InformReTransmissionsActive_b;                  /* Flag to mark that retransmissions for INFORM message are currently enabled */

}rba_EthDHCPClient_Table_tst;

/*
 * DHCP Option table
 */
typedef struct
{
    uint32                          rxOptionServerId_u32;
    uint32                          rxOptionLeaseTime_u32;
    uint32                          rxOptionSubnetMaskId_u32;
    uint32                          rxOptionRouter_u32;
    uint32                          rxOptionRenewalTime_u32;
    uint32                          rxOptionRebindingTime_u32;

    uint16                          rxOptionFQDNLen_u16;
    uint8                           rxFQDNTempBufr_au8[RBA_ETHDHCP_OPTION_FQDN_MAX_LENGTH];
    uint8                           rxOptionMessType_u8;


    boolean                         rxOptionMessTypeRxFlag_b;           /* Flag to indicate that a Message Type has been received   */
    boolean                         rxOptionServerIdRxFlag_b;           /* Flag to indicate that a Server Id has been received      */
    boolean                         rxOptionLeaseTimeRxFlag_b;          /* Flag to indicate that a Lease Time has been received     */
    boolean                         rxOptionRenewalTimeRxFlag_b;        /* Flag to indicate that a Renew Time has been received     */
    boolean                         rxOptionRebindingTimeRxFlag_b;      /* Flag to indicate that a Rebind Time has been received    */
    boolean                         rxOptionSubnetMaskIdRxFlag_b;       /* Flag to indicate that a Subnet Mask has been received    */
    boolean                         rxOptionRouterRxFlag_b;         /* Flag to indicate that an IP Address for Router has been received */



}rba_EthDHCPClient_OptionsTable_tst;

#endif  /* #if ( defined(TCPIP_DHCP_CLIENT_ENABLED) && ( TCPIP_DHCP_CLIENT_ENABLED == STD_ON ) ) */

#endif /* RBA_ETHDHCPCLIENT_TYPES_H */


