
#define MEMMAP_ERROR
/* MR12 RULE 4.10, 20.5 VIOLATION:  4.10: Memmap file must be included multiple times,  20.5: AUTOSAR MemMap concept requires #undef, AUTOSAR MemMap requirements are incompatible to MISRA */
#if defined STBM_START_SEC_CODE
  #undef STBM_START_SEC_CODE
  #undef MEMMAP_ERROR
#elif defined STBM_STOP_SEC_CODE
  #undef STBM_STOP_SEC_CODE
  #undef MEMMAP_ERROR
#elif defined STBM_START_SEC_CONST_UNSPECIFIED
  #undef STBM_START_SEC_CONST_UNSPECIFIED
  #undef MEMMAP_ERROR
#elif defined STBM_STOP_SEC_CONST_UNSPECIFIED
  #undef STBM_STOP_SEC_CONST_UNSPECIFIED
  #undef MEMMAP_ERROR
#elif defined STBM_START_SEC_VAR_CLEARED_16
  #undef STBM_START_SEC_VAR_CLEARED_16
  #undef MEMMAP_ERROR
#elif defined STBM_STOP_SEC_VAR_CLEARED_16
  #undef STBM_STOP_SEC_VAR_CLEARED_16
  #undef MEMMAP_ERROR
#elif defined STBM_START_SEC_VAR_CLEARED_32
  #undef STBM_START_SEC_VAR_CLEARED_32
  #undef MEMMAP_ERROR
#elif defined STBM_STOP_SEC_VAR_CLEARED_32
  #undef STBM_STOP_SEC_VAR_CLEARED_32
  #undef MEMMAP_ERROR
#elif defined STBM_START_SEC_VAR_CLEARED_8
  #undef STBM_START_SEC_VAR_CLEARED_8
  #undef MEMMAP_ERROR
#elif defined STBM_STOP_SEC_VAR_CLEARED_8
  #undef STBM_STOP_SEC_VAR_CLEARED_8
  #undef MEMMAP_ERROR
#elif defined STBM_START_SEC_VAR_CLEARED_UNSPECIFIED
  #undef STBM_START_SEC_VAR_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR
#elif defined STBM_STOP_SEC_VAR_CLEARED_UNSPECIFIED
  #undef STBM_STOP_SEC_VAR_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR
#elif defined STBM_START_SEC_VAR_CLEARED_UNSPECIFIED
  #undef STBM_START_SEC_VAR_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR
#elif defined STBM_STOP_SEC_VAR_CLEARED_UNSPECIFIED
  #undef STBM_STOP_SEC_VAR_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR
#elif defined STBM_START_SEC_VAR_INIT_8
  #undef STBM_START_SEC_VAR_INIT_8
  #undef MEMMAP_ERROR
#elif defined STBM_STOP_SEC_VAR_INIT_8
  #undef STBM_STOP_SEC_VAR_INIT_8
  #undef MEMMAP_ERROR
#elif defined STBM_START_SEC_VAR_INIT_UNSPECIFIED
  #undef STBM_START_SEC_VAR_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR
#elif defined STBM_STOP_SEC_VAR_INIT_UNSPECIFIED
  #undef STBM_STOP_SEC_VAR_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR
#elif defined STBM_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
  #undef STBM_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
  #undef MEMMAP_ERROR
#elif defined STBM_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
  #undef STBM_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
  #undef MEMMAP_ERROR
#elif defined StbM_START_SEC_CODE
  #undef StbM_START_SEC_CODE
  #undef MEMMAP_ERROR
#elif defined StbM_STOP_SEC_CODE
  #undef StbM_STOP_SEC_CODE
  #undef MEMMAP_ERROR
#endif
#ifdef MEMMAP_ERROR
#error "StbM_MemMap.h, wrong pragma command"
#endif
